name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - run: nix develop -c wasm-pack build --target web --release
    - run: nix develop -c npm publish ./pkg
